// <auto-generated />
using Bulky.DataAccess.Data;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;


#nullable disable

namespace Bulky.DataAccess.Migrations
{
	[DbContext(typeof(AppDBContext))]
	[Migration("20241124231005_UpdateSeededCategoryTable")]
	partial class UpdateSeededCategoryTable
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "9.0.0")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("BulkyWeb.Models.Category", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

					b.Property<int>("DisplayOrder")
						.HasColumnType("integer");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("Id");

					b.ToTable("Catogories");

					b.HasData(
						new
						{
							Id = 1,
							DisplayOrder = 1,
							Name = "Action"
						},
						new
						{
							Id = 2,
							DisplayOrder = 2,
							Name = "SciFi"
						},
						new
						{
							Id = 3,
							DisplayOrder = 3,
							Name = "Horror"
						});
				});
#pragma warning restore 612, 618
		}
	}
}
